name: Azure CI-CD

on:
  push:
    branches: [ "main" ] # This triggers the belt when you push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Login to Azure Container Registry'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: 'Build and Push Image'
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/ingredient-ai:${{ github.sha }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/ingredient-ai:${{ github.sha }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'resepin-api'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: '${{ secrets.ACR_LOGIN_SERVER }}/ingredient-ai:${{ github.sha }}'